services:
  device:
    build: ./smart-home-microservice/device
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-device:5432/device
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_DEVICE_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_DEVICE_PASSWORD:-password}
    ports:
      - ${DEVICE_PORT:-8081}:8080
    depends_on:
      - postgres-device
    networks:
      - smart-home-network

  telemetry:
    build: ./smart-home-microservice/telemetry
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-telemetry:5432/telemetry
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_DEVICE_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_DEVICE_PASSWORD:-password}
    ports:
      - ${TELEMETRY_PORT:-8082}:8080
    depends_on:
      - postgres-telemetry
    networks:
      - smart-home-network
#
  postgres-device:
    image: postgres:13-alpine
    hostname: postgres-device
    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-device:5432/device
      POSTGRES_DB: device
      POSTGRES_USER: ${POSTGRES_DEVICE_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_DEVICE_PASSWORD:-password}
    ports:
      - ${POSTGRES_DEVICE_DB_PORT:-5432}:5432
    volumes:
      - postgres-device-data:/var/lib/postgresql/data
    networks:
      - smart-home-network

  postgres-telemetry:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: telemetry
      POSTGRES_USER: ${POSTGRES_TELEMETRY_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_TELEMETRY_PASSWORD:-password}
    ports:
      - ${POSTGRES_TELEMETRY_DB_PORT:-5433}:5432
    volumes:
      - postgres-telemetry-data:/var/lib/postgresql/data
    networks:
      - smart-home-network

  kong:
    container_name: kong
    image: kong
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: warn
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yaml
      KONG_ADMIN_GUI_PATH: '/'
      KONG_ADMIN_GUI_URL: 'http://localhost:8002/manager'
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl, 0.0.0.0:9080 http2, 0.0.0.0:9081 http2 ssl
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./kong.yaml:/usr/local/kong/declarative/kong.yaml
    ports:
      - "8001:8001" # admin
      - "8444:8444" # admin ssl
      - "8002:8002" # admin gui
      - "8445:8445" # admin gui ssl
      - "8000:8000" # proxy
      - "8443:8443" # proxy ssl
      - "9080:9080" # proxy http2
      - "9081:9081" # proxy http2 ssl
    networks:
      - smart-home-network


volumes:
  postgres-device-data:
  postgres-telemetry-data:

networks:
  smart-home-network:
    driver: bridge

