@startuml
title Диаграмма контекста Умного дома

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "Пользователь", "Пользователь системы Умный дом")
Person(admin, "Администратор", "Администратор системы Умный дом")
System(SmartHomeSystem, "Система Умный дом", "Устанавливает и мониторит температуру дома")

System_Ext(sensor, "Устройства", "API устройств", "Использует REST API, формат данных JSON")
Rel(user, SmartHomeSystem, "Использует систему Умный дом")
Rel(admin, SmartHomeSystem, "Управляет системой Умный дом")
Rel(SmartHomeSystem, sensor, "Получает данные о температуре, отправляет команды")

@enduml
