openapi: 3.1.0
info:
  title: Device Service API
  description: API микросервиса устройств, который управляет данными об устройствах и отправляет команды на устройства.
  version: 0.1.0

paths:
  /api/devices:
    post:
      summary: Добавить новое устройство
      description: Создает новое устройство и сохраняет его в базе данных.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                deviceTypeId:
                  type: integer
                  format: int64
                  description: Идентификатор типа устройства
                  example: '22'
                moduleId:
                  type: string
                  format: uuid
                  description: Идентификатор модуля, к которому подключено устройство
                  example: '7c19761d-a3c4-4f42-9ae1-ed9850ffd381'
                scenarioId:
                  type: string
                  format: uuid
                  description: Идентификатор сценария использования устройства, который будет выполняться на данном устройстве
                  example: '91a0c88c-6933-4bc1-ab27-3e5a1c45bb74'
                name:
                  type: string
                  description: Название устройства
                  example: 'Thermostat'
                serialNumber:
                  type: string
                  description: Серийный номер устройства
                  example: 'HD-156133'
      responses:
        '201':
          description: Устройство успешно добавлено
        '400':
          description: Неверный запрос
        '500':
          description: Ошибка сервера

  /api/devices/{id}:
    get:
      summary: Получить информацию об устройстве
      description: Возвращает подробную информацию об устройстве по его ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
            description: Уникальный идентификатор устройства
            example: '7c19761d-a3c4-4f42-9ae1-ed9850ffd381'
      responses:
        '200':
          description: Информация об устройстве
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    description: Уникальный идентификатор устройства
                    example: '7c19761d-a3c4-4f42-9ae1-ed9850ffd381'
                  deviceTypeId:
                    type: integer
                    format: int64
                    description: Идентификатор типа устройства
                    example: '22'
                  moduleId:
                    type: string
                    format: uuid
                    description: Идентификатор модуля, к которому подключено устройство
                    example: '7c19761d-a3c4-4f42-9ae1-ed9850ffd381'
                  scenarioId:
                    type: string
                    format: uuid
                    description: Идентификатор сценария использования устройства, который будет выполняться на данном устройстве
                    example: '91a0c88c-6933-4bc1-ab27-3e5a1c45bb74'
                  name:
                    type: string
                    description: Название устройства
                    example: 'Thermostat'
                  serialNumber:
                    type: string
                    description: Серийный номер устройства
                    example: 'HD-156133'
                  currentValue:
                    type: number
                    format: double
                    description: Текущее значение устройства
                    example: '19'
                  targetValue:
                    type: number
                    format: double
                    description: Целевое значение устройства
                    example: '23.5'
                  status:
                    type: string
                    description: Текущее состояние устройства (включено/выключено)
                    example: 'on'
        '404':
          description: Устройство не найдено
        '500':
          description: Ошибка сервера

    put:
      summary: Обновить информацию об устройстве
      description: Обновляет информацию об устройстве по его ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор устройства
          example: '7c19761d-a3c4-4f42-9ae1-ed9850ffd381'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                deviceTypeId:
                  type: integer
                  format: int64
                  description: Идентификатор типа устройства
                  example: '22'
                moduleId:
                  type: string
                  format: uuid
                  description: Идентификатор модуля, к которому подключено устройство
                  example: '7c19761d-a3c4-4f42-9ae1-ed9850ffd381'
                scenarioId:
                  type: string
                  format: uuid
                  description: Идентификатор сценария использования устройства, который будет выполняться на данном устройстве
                  example: '91a0c88c-6933-4bc1-ab27-3e5a1c45bb74'
                name:
                  type: string
                  description: Название устройства
                  example: 'Thermostat'
                serialNumber:
                  type: string
                  description: Серийный номер устройства
                  example: 'HD-156133'
                currentValue:
                  type: number
                  format: double
                  description: Текущее значение устройства
                  example: '19'
                targetValue:
                  type: number
                  format: double
                  description: Целевое значение устройства
                  example: '23.5'
      responses:
        '200':
          description: Статус устройства обновлен
        '400':
          description: Некорректный запрос
        '404':
          description: Устройство не найдено
        '500':
          description: Ошибка сервера

    delete:
      summary: Удалить устройство
      description: Удаляет устройство по его ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор устройства
          example: '7c19761d-a3c4-4f42-9ae1-ed9850ffd381'
      responses:
        '204':
          description: Устройство успешно удалено
        '404':
          description: Устройство не найдено
        '500':
          description: Ошибка сервера

  /api/devices/{id}/status:
    put:
      summary: Обновить статус устройства
      description: Обновляет статус устройства.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор устройства
          example: '7c19761d-a3c4-4f42-9ae1-ed9850ffd381'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  example: 'on'
      responses:
        '204':
          description: Статус устройства обновлен
        '400':
          description: Некорректный запрос
        '404':
          description: Устройство не найдено
        '500':
          description: Ошибка сервера

  /api/devices/{id}/command:
    post:
      summary: Отправить команду на устройство
      description: Отправляет команду устройству на выполнение.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор устройства
          example: '7c19761d-a3c4-4f42-9ae1-ed9850ffd381'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                command:
                  type: string
                  example: "set_temperature 23.5"
      responses:
        '204':
          description: Команда отправлена на устройство
        '404':
          description: Команда не найдена
        '500':
          description: Ошибка сервера

  /api/device-types:
    post:
      summary: Добавить новый тип устройства
      description: Создает нового типа устройства и сохраняет его в базе данных.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Название типа устройства
                  example: 'heating'
                description:
                  type: string
                  description: Описание типа устройства
                  example: 'Тип устройства отопительной системы дома'
      responses:
        '201':
          description: Тип устройства успешно добавлен
        '400':
          description: Неверный запрос
        '500':
          description: Ошибка сервера

  /api/device-types/{id}:
    get:
      summary: Получить информацию о типе устройства
      description: Возвращает подробную информацию о типе устройства.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            description: Уникальный идентификатор типа устройства
            example: '75'
      responses:
        '200':
          description: Информация о типе устройства
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    description: Уникальный идентификатор типа устройства
                    example: '1'
                  name:
                    type: string
                    description: Название типа устройства
                    example: 'heating'
                  description:
                    type: string
                    description: Описание типа устройства
                    example: 'Тип устройства отопительной системы дома'
        '404':
          description: Тип устройства не найден
        '500':
          description: Ошибка сервера
      put:
        summary: Обновить информацию о типе устройства
        description: Обновляет информацию о типе устройства.
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: integer
              format: int64
            description: Идентификатор типа устройства
            example: '22'
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Название типа устройства
                    example: 'heating'
                  description:
                    type: string
                    description: Описание типа устройства
                    example: 'Тип устройства отопительной системы дома'
        responses:
          '200':
            description: Тип устройства обновлен
          '400':
            description: Некорректный запрос
          '404':
            description: Тип устройства не найден
          '500':
            description: Ошибка сервера

    delete:
      summary: Удалить тип устройства
      description: Удаляет тип устройства.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: Идентификатор типа устройства
          example: '22'
      responses:
        '204':
          description: Тип устройства успешно удалено
        '404':
          description: Тип устройства не найдено
        '500':
          description: Ошибка сервера
